### ISSUE TITLE
EPIC: Migrate API to django-ninja

### ISSUE THREAD

**Issue by robhudson** [mozmeao/basket#1530]
## Description:

Migrate basket API to django-ninja.

Django-ninja offers:
* **Built-in Data Validation**: Django Ninja offers automatic request and response validation using Pydantic
* **Type Safety**: With type hints, we can ensure type correctness on request and response data, making code more reliable and consistent across APIs and responses
* **Auto-Generated Documentation**: Django Ninja automatically generates an OpenAPI schema, making API documentation consistent and easy to update, and providing a user-friendly interface for using or testing the API

### Tasks

**Keep the same URL but move to django-ninja**
- [ ] `/news/newsletters/`
- [ ] `/news/subscribe/`: This is a form-encoded endpoint.
- [ ] `/news/unsubscribe/<uuid:token>/`
- [ ] `/news/custom_unsub_reason/`

**Move to new URL along with move to django-ninja**
- [ ] `/news/user/<uuid:token>/` -> `/users/<uuid:token>/`
- [ ] `/news/user-meta/<uuid:token>/` -> `/users/meta/<uuid:token>/`
- [ ] `/news/lookup-user/` -> `/users/lookup/`
- [ ] `/news/confirm/<uuid:token>/` -> `/users/confirm/<uuid:token>/` 
- [ ] `/news/recover/` -> `/users/recover/`

### TBD
- `/news/common-voice-goals/` - we still get data here.

All other URLs will remain as-is.
